version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=discus_dev
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres